In [12]:
import pandas as pd
import numpy as np
import seaborn as sns

In [13]:
data = sns.load_dataset('titanic')

In [14]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [15]:

data['embark_town'] = data['embark_town'].astype('category')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    category
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(3), float64(2), int64(4), object(4)
memory usage: 74.7+ KB

In [17]:
data['new_col'] = data['embark_town'].str[0]

In [18]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new_col
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,S
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,C
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,S
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,S
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,S

In [19]:
data.shape

(891, 16)

In [25]:
count = 0
for i in range(len(data)):
    if data['embarked'].iloc[i] != data['new_col'].iloc[i]:
        count = count + 1
        print((data['embark_town'].iloc[i]))
        print((data['embarked']).iloc[i])
            
print(count)

nan
nan
nan
nan
2

In [26]:
mismatch = data[data['embarked'] != data['new_col']]
print(len(mismatch))

2

In [27]:
data

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,new_col
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,S
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,C
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,S
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,S
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,S
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,S
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,S
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,C
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Q

In [35]:
list1 = data['embarked'].unique()
list2 = data['embark_town'].unique()

mapping = dict(zip(list1,list2))
mapping
print(data.shape)

matched = data[data['embarked'].map(mapping) == data['embark_town']]
print(matched.shape)


not_matched = data.loc[data['embarked'].map(mapping) != data['embark_town']]
print(not_matched)

(891, 16)
(889, 16)
     survived  pclass     sex   age  sibsp  parch  fare embarked  class  \
61          1       1  female  38.0      0      0  80.0      NaN  First
829         1       1  female  62.0      0      0  80.0      NaN  First

       who  adult_male deck embark_town alive  alone new_col
61   woman       False    B         NaN   yes   True     NaN
829  woman       False    B         NaN   yes   True     NaN

In [37]:
print(np.nan == np.nan)
# False because they are not getting compared

False